language: ruby
rvm:
  - 2.3.0

services:
  - postgresql

script:
  - bundle exec rspec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:create
