language: ruby
rvm:
  - 2.3.0

addons:
  postgresql: "9.5.2"

services:
  - postgresql

script:
  - bundle exec rspec

before_script:
  - cp config/database.yml.travis config/database.yml  
  - psql -c 'create database travis_ci_test;' -U yuliya
